# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec83e1dc8e11e5a648e47f5c25c490e13b079777c251794ed013414c83a00d32a6af0e0ed33a22b4c9b37c6b500f15cfce7b8c61f221cdd46f9742ee696ce83

test:
  secret_key_base: 92ae83937bfcedc3f30fb1729e953712ef7ac5b4247010302008f9f75f53f7a0aa66b13e8e8b64cde387a68b4bc17d3d66c6b9f577577ff5748e0bf08afdab9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
